### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by hippien** [MasterAM/meteor-ol3#5]
'meteor build' with 'alon:ol3' on Windows is failing. It's successful on Mac. Starting application with just 'meteor' is working but as said 'meteor build' or 'meteor deploy' is failing.
Meteor version is **Meteor 1.2.1**

Reproduce error:

```
>meteor create alonol3
>cd alonol3
>meteor build --directory ..\build\alonol3
>meteor add alon:ol3
>meteor build --directory ..\build\alonol3
```

The last build command after the alon:ol3 was added will generate this error:

```
C:\Users\username\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:245
                                                throw(ex);
                                                      ^
TypeError: Cannot call method 'split' of undefined
    at Object.parse (C:\tools\utils\parse-stack.js:18:28)
    at Object.exception (C:\tools\utils\buildmessage.js:489:29)
    at C:\tools\isobuild\bundler.js:889:22
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at ClientTarget.minifyJs (C:\tools\isobuild\bundler.js:884:18)
    at C:\tools\isobuild\bundler.js:529:16
    at C:\tools\utils\buildmessage.js:356:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:349:34
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:347:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
    at ClientTarget.make (C:\tools\isobuild\bundler.js:491:18)
    at C:\tools\isobuild\bundler.js:2143:14
    at C:\tools\isobuild\bundler.js:2232:20
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\username\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_module
s\underscore\underscore.js:79:11)
    at C:\tools\isobuild\bundler.js:2231:7
    at C:\tools\utils\buildmessage.js:268:13
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:261:29
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:259:18
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at C:\tools\utils\buildmessage.js:250:23
    at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
    at Object.capture (C:\tools\utils\buildmessage.js:249:19)
    at Object.exports.bundle (C:\tools\isobuild\bundler.js:2128:31)
    at buildCommand (C:\tools\cli\commands.js:916:30)
    at Command.main.registerCommand._.extend.name [as func] (C:\tools\cli\commands.js:791:12)
    at C:\tools\cli\main.js:1378:23

C:\SourceCode\Projects\meteor\alonol3>
```

**Comment by MasterAM** [comment]
Hi,
Thanks for reporting the issue.

It is related to _ugllify.js_. The actual error is that the stack size is exceeded, due to the fact that one of the OpenLayers functions contains more statements than the minifier can handle with the current stack size.

I will create a bug report regarding this issue, but in the mean time, it is best to avoid building the package using Windows.
